# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ce6a4fe1f7d32a080a222de92fafbe585f02764c66ea295d327cded720a598f3f539bf4e51c2044088a4dc130850432ab512f9e1f617cdf10c2f938db8a6ba

test:
  secret_key_base: 6be1dc6b23e0a6bd68a14ad92ea238ba9a973c77d7bda0fe44d8088ce7b82d4eee4a3fa32159ebcd00b700d4a9ee05d5a17c2e1acd96359426452deb2d964f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
